aws:
  bucket: 'bucket-projeto-integrado-usjt'
  bucket_dest: 'bucket-projeto-integrado-usjt-processed'
file:
  path: 'newcsv.csv'
rabbit:
  host: 'localhost'
  port: 5672
  user: 'guest'
  pass: 'guest'